#! /usr/bin/python
import os
import sys

if len(sys.argv) == 2:
    python_v = sys.argv[1]

try:
    import pyautogui as x
    from pynput.keyboard import Key, Listener
except:
    os.system("sudo pip install pyautogui")
    try:
        from pynput.keyboard import Key, Listener
    except:
        os.system("sudo pip install pynput")
    print("\t restart sript!")
    exit(0)
def on_press(key):
    if str(key) == "'s'":
        x.press("backspace")
        x.sleep(.5)
        x.write(f"\n{python_v} -c 'import pty;pty.spawn(\"/bin/bash\")'\n")
        x.sleep(.5)
        x.write("export TERM=xterm;\n")
        x.sleep(.5)
        x.hotkey("ctrl","z")
        x.sleep(.5)
        x.write("stty raw -echo; fg\n\n")
        exit(0)

print("when You ready press s")
with Listener(
        on_press=on_press
        ) as listener:
    listener.join()
