#!/bin/bash

# Get the output of the "ip a" command
output=$(ip a)

# The regular expression pattern to match an IP address
pattern="\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"

# Find all matches of the pattern in the output
matches=$(echo "$output" | grep -Eo $pattern)

# Print out all matches
printf "\t\t WGET\n"
for match in $matches; do
    echo "wget http://$match:4444/$1"
done

printf "\n\t\t CURL\n"
for match in $matches; do
    echo "curl -O http://$match:4444/$1"
done
python -m http.server 4444
